# -*- coding: utf-8 -*-
"""JSS_Prophet_ML_Futures_StockBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QJ7-HO7gR61Ik1FktagJyO687N7Kkta7
"""

#Facebook Prophet is an open-source tool developed by Facebook's Core Data Science team, designed specifically for time series forecasting.
#It's a robust machine-learning model that works well with daily observations that have seasonal patterns
!pip install pystan

!pip install prophet #FBprophet was renamed to prophet

!pip install pandas-datareader
!pip install pandas

import pandas as pd

#import datetime as dt             #tried to create csv from web however was returning obejct type error so downloaded package from the internet
#import pandas_datareader as web

#start = dt.datetime(2015, 1, 1)
#end = dt.datetime.now()

#data = web.DataReader("SQ", "yahoo")
#data.to_csv("SQ_data.csv")

##Can collect data from yfinance without creating csv##

#import yfinance as yf
#import datetime as dt

#start = dt.datetime(2015, 1, 1)
#end = dt.datetime.now()

#stock = "SQ"
#blockinc_data = yf.download(stock, start, end)
#blockinc_data.head()

data = pd.read_csv("SQ_stock_data.csv")
data.head()